[application]

name = "Job Tracker"

[web.app]

[web.watcher]

[web.resource]

[web.resource.dev]

[bundle]
identifier = "com.fios-quest.job-tracker"
publisher = "Fios Quest"

icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico"
]
